### ISSUE TITLE
Create Sponsorship Brochure 

### ISSUE THREAD

**Issue by KangkanS** [iGEM-Bettencourt-2021/Marketing-and-Communications#3]
Design a brochure to include in emails to sponsors. Should give a general overview of our project and have our logo design (Sophie) added on the front

**Comment by AbhayKoushik** [comment]
Hey,

The Brochure design group has been up and going! Feel free to keep yourself updated with our progress [here](https://drive.google.com/drive/folders/1zIUwEtmkUN6NCzdQu9z7iKDF6SeUt5qP?usp=sharing).

Cheers!
Abhay

**Comment by JulianQ22** [comment]
After meeting with Legal and Finance as well as with the Leads, to improve equity and fairness in the way sponsors can contribute to our project we should change our approach for the sponsorship brochure : 

+ Rather than trying to make them fit pre-designed boxes (Platinium, Gold, Silver, ...) we should deal with them as a case by case thing.
+ Also apparently we have sufficient funds not to worry about money, so we should rather ask for _in kind_ sponsorships (scientific/technical expertise and/or lab material) than _in cash_.

+ We propose them our advertising solutions for their company (in our brochure) and see which ones they want to choose in turn. They might not be all wanting the same type of sponsorship/advertising ! (E.g. merch sponsoring will not be suitable for specialists from which we get expertise, whereas on the contrary larger companies might like that).
+ Of course the more a partner wants to be sponsored, the more it should contribute (again, it must be a personalized negociation case by case).

**Comment by JulianQ22** [comment]
@git-cgalan mentionned a very interesting point : 

iGEM has regular sponsors which are giving out some of their product for free, two examples : 
+ _IDT's generous offer of 20,000 bases of FREE DNA synthesis to all iGEM teams_
+ _Twist Bioscience has teamed up with iGEM to offer every team complimentary synthesis of up to 10kb in Twist Gene Fragments_
+ https://2020.igem.org/Sponsors

Knowing this we can already adapt our sponsors targeting strategy to the ones we would really need to reach out.

**Comment by JulianQ22** [comment]
Also, we might have to do two versions of the brochure proposing two different set of sponsoring/advertising solutions :
 
+ one for the specialists/institutes we want expertise from on a given matter (mostly helping us on the wet lab and dry lab I guess).
+ one for the companies providing material for wet lab experiments.

**Comment by AbhayKoushik** [comment]
Thanks for all these inputs, Julian! 

- Makes sense to scrap the idea of fixed design boxes if we are focused more about in-kind sponsorship.
- Let's discuss on how we could bring in the ideas for contribution negotiations with in the next meet.
- I just added in a new issue here for all our sponsorship resources, feel free to frequently update all things relevant there.
- Adding the specialist - companies idea discussion on our agenda for the next meeting.

Cheers,
Abhay
